spring:
  application:
    name: "spring-cloud-stream-multibinder"
  cloud:
    function:
      definition: text-producer;text-length-processor;length-consumer
    stream:
      bindings:
        text-producer-out-0:
          destination: "${kafka.topic.texts}"
          binder: kafka1
        text-length-processor-in-0:
          destination: "${kafka.topic.texts}"
          binder: kstream1
        text-length-processor-out-0:
          destination: "${kafka.topic.lengths}"
          binder: kstream1
        length-consumer-in-0:
          destination: "${kafka.topic.lengths}"
          group: "${spring.application.name}"
          binder: kafka1
      binders:
        kafka1:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: "${kafka.brokers}"
        kstream1:
          type: kstream
          environment:
            spring.cloud.stream.kafka.streams.binder:
              applicationId: "${spring.application.name}-KApp"
              brokers: "${kafka.brokers}"

server:
  port: 8080

kafka:
  brokers: "localhost:9094"
  topic:
    texts: "pub.texts"
    lengths: "pub.lengths"
